// Builds supabase/tests/database/name_rules.generated.test.sql from the
// app's rules and examples, so the database is tested against exactly
// what the app expects. Written by `npm run gen:name-tests`;
// name-rules.test.ts fails if the file is out of date.

import { NAME_CASES } from './name-cases.ts';
import {
  checkName,
  EMOJI,
  EMOJI_STYLE,
  NAME_MAX,
  type NameKind,
  REFUSED,
  SKIN_TONES,
  SPACES,
  ZWJ,
} from './name-rules.ts';

/** A Postgres string literal for any text: U&'...' with escapes. */
export function sqlText(s: string | null): string {
  if (s === null) return 'null::text';
  let out = '';
  for (const c of s) {
    const cp = c.codePointAt(0)!;
    if (c === "'") out += "''";
    else if (c === '\\') out += '\\\\';
    else if (cp >= 0x20 && cp < 0x7f) out += c;
    else if (cp <= 0xffff) out += '\\' + cp.toString(16).padStart(4, '0');
    else out += '\\+' + cp.toString(16).padStart(6, '0');
  }
  return `U&'${out}'`;
}

const hex = (cp: number) => 'U+' + cp.toString(16).toUpperCase().padStart(4, '0');
const usable = (cp: number) => cp > 0 && cp <= 0x10ffff && !(cp >= 0xd800 && cp <= 0xdfff);

/** Every range edge, just inside and just outside, in a few settings. */
function edgeCases(): { label: string; raw: string; kind: NameKind }[] {
  const points = new Set<number>();
  for (const [from, to] of [...REFUSED, ...SPACES, ...EMOJI, SKIN_TONES]) {
    for (const cp of [from - 1, from, to, to + 1]) if (usable(cp)) points.add(cp);
  }
  for (const cp of [ZWJ, EMOJI_STYLE]) points.add(cp);
  const sorted = [...points].sort((a, b) => a - b);
  const smile = String.fromCodePoint(0x1f600);
  return sorted.flatMap((cp) => {
    const c = String.fromCodePoint(cp);
    return [
      { label: `${hex(cp)} between letters`, raw: `a${c}b`, kind: 'display' as const },
      { label: `${hex(cp)} then emoji style`, raw: `${c}️`, kind: 'display' as const },
      { label: `${hex(cp)} then joiner and emoji`, raw: `${c}‍${smile}`, kind: 'display' as const },
    ];
  });
}

export function nameTestsSql(): string {
  const cases = [
    ...NAME_CASES.map((c) => ({ label: c.label, raw: c.raw, kind: c.kind })),
    ...edgeCases(),
  ];
  const lines = cases.map(({ label, raw, kind }) => {
    const result = checkName(raw, kind);
    const expected = result.ok ? result.name : null;
    return (
      `select is(public.name_shape(${sqlText(raw)}, ${NAME_MAX[kind]}), ${sqlText(expected)},\n` +
      `          ${sqlText(`${kind}: ${label}`)});`
    );
  });
  return [
    '-- GENERATED by `npm run gen:name-tests` from src/auth/name-rules.ts and',
    '-- src/auth/name-cases.ts. Do not edit: change those files and run it again.',
    '-- Checks the database shapes names exactly as the app does',
    '-- (step-tracker-safety.txt, section 6). Run with `supabase test db`.',
    'begin;',
    'create extension if not exists pgtap with schema extensions;',
    `select plan(${lines.length});`,
    '',
    ...lines,
    '',
    'select * from finish();',
    'rollback;',
    '',
  ].join('\n');
}
