-- GENERATED by `npm run gen:name-tests` from src/auth/name-rules.ts and
-- src/auth/name-cases.ts. Do not edit: change those files and run it again.
-- Checks the database shapes names exactly as the app does
-- (step-tracker-safety.txt, section 6). Run with `supabase test db`.
begin;
create extension if not exists pgtap with schema extensions;
select plan(605);

select is(public.name_shape(U&'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 30), U&'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
          U&'display: 30 characters');
select is(public.name_shape(U&'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 30), null::text,
          U&'display: 31 characters');
select is(public.name_shape(U&'yyyyyyyyyyyyyyy', 15), U&'yyyyyyyyyyyyyyy',
          U&'group: group: 15 characters');
select is(public.name_shape(U&'yyyyyyyyyyyyyyyy', 15), null::text,
          U&'group: group: 16 characters');
select is(public.name_shape(U&'Q', 30), U&'Q',
          U&'display: one character');
select is(public.name_shape(U&'', 30), null::text,
          U&'display: empty');
select is(public.name_shape(U&'   ', 30), null::text,
          U&'display: spaces only');
select is(public.name_shape(U&'\00a0', 30), null::text,
          U&'display: non-breaking space only');
select is(public.name_shape(U&'\3000\3000', 30), null::text,
          U&'display: ideographic space only');
select is(public.name_shape(U&'  Ana Lee  ', 30), U&'Ana Lee',
          U&'display: trimmed at both ends');
select is(public.name_shape(U&'Ana\00a0Lee', 30), U&'Ana Lee',
          U&'display: non-breaking space inside becomes a space');
select is(public.name_shape(U&'\3000Ana\2003', 30), U&'Ana',
          U&'display: leading and trailing Unicode spaces removed');
select is(public.name_shape(U&'Ana \00a0 \2009 Lee', 30), U&'Ana Lee',
          U&'display: runs of spaces collapse to one');
select is(public.name_shape(U&' xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ', 30), U&'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
          U&'display: spaces do not count towards the limit');
select is(public.name_shape(U&'Ana\000aLee', 30), null::text,
          U&'display: line feed inside');
select is(public.name_shape(U&'Ana\000dLee', 30), null::text,
          U&'display: carriage return inside');
select is(public.name_shape(U&'Ana\0009Lee', 30), null::text,
          U&'display: tab inside');
select is(public.name_shape(U&'Ana\000a', 30), null::text,
          U&'display: line feed at the end');
select is(public.name_shape(U&'Ana\0085Lee', 30), null::text,
          U&'display: U+0085 next line');
select is(public.name_shape(U&'Ana\2028Lee', 30), null::text,
          U&'display: U+2028 line separator');
select is(public.name_shape(U&'Ana\2029Lee', 30), null::text,
          U&'display: U+2029 paragraph separator');
select is(public.name_shape(U&'Ana\200b', 30), null::text,
          U&'display: zero-width space at the end');
select is(public.name_shape(U&'sh\200bit', 30), null::text,
          U&'display: zero-width space splitting a word');
select is(public.name_shape(U&'Ana\200cLee', 30), null::text,
          U&'display: zero-width non-joiner');
select is(public.name_shape(U&'Ana\2060Lee', 30), null::text,
          U&'display: word joiner');
select is(public.name_shape(U&'\feffAna', 30), null::text,
          U&'display: byte order mark');
select is(public.name_shape(U&'An\00ada', 30), null::text,
          U&'display: soft hyphen');
select is(public.name_shape(U&'Ana\202eeL', 30), null::text,
          U&'display: right-to-left override');
select is(public.name_shape(U&'Ana\200e', 30), null::text,
          U&'display: left-to-right mark');
select is(public.name_shape(U&'\2068Ana', 30), null::text,
          U&'display: first strong isolate');
select is(public.name_shape(U&'\2800', 30), null::text,
          U&'display: braille blank only');
select is(public.name_shape(U&'\3164', 30), null::text,
          U&'display: Hangul filler only');
select is(public.name_shape(U&'Ana\2800Lee', 30), null::text,
          U&'display: braille blank inside');
select is(public.name_shape(U&'Ana\fe0e', 30), null::text,
          U&'display: text-style variation selector');
select is(public.name_shape(U&'Ana\+0e0067\+0e0062', 30), null::text,
          U&'display: tag characters');
select is(public.name_shape(U&'\+01f468\200d\+01f469\200d\+01f467', 30), U&'\+01f468\200d\+01f469\200d\+01f467',
          U&'display: family emoji (joiners between emoji)');
select is(public.name_shape(U&'\2764\fe0f', 30), U&'\2764\fe0f',
          U&'display: red heart with emoji style');
select is(public.name_shape(U&'\+01f44d\+01f3fd', 30), U&'\+01f44d\+01f3fd',
          U&'display: thumbs up with a skin tone');
select is(public.name_shape(U&'\+01f469\+01f3fd\200d\+01f4bb', 30), U&'\+01f469\+01f3fd\200d\+01f4bb',
          U&'display: woman technologist, skin tone then joiner');
select is(public.name_shape(U&'\+01f3f3\fe0f\200d\+01f308', 30), U&'\+01f3f3\fe0f\200d\+01f308',
          U&'display: rainbow flag (emoji style then joiner)');
select is(public.name_shape(U&'Ana \+01f1fa\+01f1f8', 30), U&'Ana \+01f1fa\+01f1f8',
          U&'display: flag (two regional indicators)');
select is(public.name_shape(U&'a\200db', 30), null::text,
          U&'display: joiner between letters');
select is(public.name_shape(U&'\+01f44d\200d', 30), null::text,
          U&'display: joiner at the end');
select is(public.name_shape(U&'\200d\+01f44d', 30), null::text,
          U&'display: joiner at the start');
select is(public.name_shape(U&'a\200d\+01f44d', 30), null::text,
          U&'display: joiner after a letter, before an emoji');
select is(public.name_shape(U&'sh\200dit', 30), null::text,
          U&'display: joiner between "sh" and "it"');
select is(public.name_shape(U&'a\fe0f', 30), null::text,
          U&'display: emoji style after a letter');
select is(public.name_shape(U&'\+01f3fd', 30), null::text,
          U&'display: skin tone alone');
select is(public.name_shape(U&'a\+01f3fd', 30), null::text,
          U&'display: skin tone after a letter');
select is(public.name_shape(U&'Jos\00e9', 30), U&'Jos\00e9',
          U&'display: \00e9 typed as one character');
select is(public.name_shape(U&'Jose\0301', 30), U&'Jos\00e9',
          U&'display: \00e9 typed as e + accent is saved as one character');
select is(public.name_shape(U&'e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301e\0301', 30), U&'\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9\00e9',
          U&'display: accented 30 typed as e + accent fits');
select is(public.name_shape(U&'xxxxxxxxxxxxxxxxxxxxxxxxx\+01f468\200d\+01f469\200d\+01f467', 30), U&'xxxxxxxxxxxxxxxxxxxxxxxxx\+01f468\200d\+01f469\200d\+01f467',
          U&'display: family emoji counts 5');
select is(public.name_shape(U&'xxxxxxxxxxxxxxxxxxxxxxxxxx\+01f468\200d\+01f469\200d\+01f467', 30), null::text,
          U&'display: family emoji over the limit');
select is(public.name_shape(U&'xxxxxxxxxxxxx\+01f1fa\+01f1f8', 15), U&'xxxxxxxxxxxxx\+01f1fa\+01f1f8',
          U&'group: group: flag counts 2');
select is(public.name_shape(U&'xxxxxxxxxxxxxx\+01f1fa\+01f1f8', 15), null::text,
          U&'group: group: flag over the limit');
select is(public.name_shape(U&'B\00e9 \+01f41d', 30), U&'B\00e9 \+01f41d',
          U&'display: emoji and accents');
select is(public.name_shape(U&'\5c71\4e0b \3055\304f\3089', 30), U&'\5c71\4e0b \3055\304f\3089',
          U&'display: Japanese');
select is(public.name_shape(U&'\0646\0648\0631', 30), U&'\0646\0648\0631',
          U&'display: Arabic');
select is(public.name_shape(U&'\092a\094d\0930\093f\092f\093e', 30), U&'\092a\094d\0930\093f\092f\093e',
          U&'display: Devanagari');
select is(public.name_shape(U&'O''Brien-Smith', 30), U&'O''Brien-Smith',
          U&'display: apostrophe and hyphen');
select is(public.name_shape(U&'Walkers \+01f6b6', 15), U&'Walkers \+01f6b6',
          U&'group: group with emoji');
select is(public.name_shape(U&'a\001fb', 30), null::text,
          U&'display: U+001F between letters');
select is(public.name_shape(U&'\001f\fe0f', 30), null::text,
          U&'display: U+001F then emoji style');
select is(public.name_shape(U&'\001f\200d\+01f600', 30), null::text,
          U&'display: U+001F then joiner and emoji');
select is(public.name_shape(U&'a b', 30), U&'a b',
          U&'display: U+0020 between letters');
select is(public.name_shape(U&' \fe0f', 30), null::text,
          U&'display: U+0020 then emoji style');
select is(public.name_shape(U&' \200d\+01f600', 30), null::text,
          U&'display: U+0020 then joiner and emoji');
select is(public.name_shape(U&'a!b', 30), U&'a!b',
          U&'display: U+0021 between letters');
select is(public.name_shape(U&'!\fe0f', 30), null::text,
          U&'display: U+0021 then emoji style');
select is(public.name_shape(U&'!\200d\+01f600', 30), null::text,
          U&'display: U+0021 then joiner and emoji');
select is(public.name_shape(U&'a~b', 30), U&'a~b',
          U&'display: U+007E between letters');
select is(public.name_shape(U&'~\fe0f', 30), null::text,
          U&'display: U+007E then emoji style');
select is(public.name_shape(U&'~\200d\+01f600', 30), null::text,
          U&'display: U+007E then joiner and emoji');
select is(public.name_shape(U&'a\007fb', 30), null::text,
          U&'display: U+007F between letters');
select is(public.name_shape(U&'\007f\fe0f', 30), null::text,
          U&'display: U+007F then emoji style');
select is(public.name_shape(U&'\007f\200d\+01f600', 30), null::text,
          U&'display: U+007F then joiner and emoji');
select is(public.name_shape(U&'a\009fb', 30), null::text,
          U&'display: U+009F between letters');
select is(public.name_shape(U&'\009f\fe0f', 30), null::text,
          U&'display: U+009F then emoji style');
select is(public.name_shape(U&'\009f\200d\+01f600', 30), null::text,
          U&'display: U+009F then joiner and emoji');
select is(public.name_shape(U&'a\00a0b', 30), U&'a b',
          U&'display: U+00A0 between letters');
select is(public.name_shape(U&'\00a0\fe0f', 30), null::text,
          U&'display: U+00A0 then emoji style');
select is(public.name_shape(U&'\00a0\200d\+01f600', 30), null::text,
          U&'display: U+00A0 then joiner and emoji');
select is(public.name_shape(U&'a\00a1b', 30), U&'a\00a1b',
          U&'display: U+00A1 between letters');
select is(public.name_shape(U&'\00a1\fe0f', 30), null::text,
          U&'display: U+00A1 then emoji style');
select is(public.name_shape(U&'\00a1\200d\+01f600', 30), null::text,
          U&'display: U+00A1 then joiner and emoji');
select is(public.name_shape(U&'a\00a8b', 30), U&'a\00a8b',
          U&'display: U+00A8 between letters');
select is(public.name_shape(U&'\00a8\fe0f', 30), null::text,
          U&'display: U+00A8 then emoji style');
select is(public.name_shape(U&'\00a8\200d\+01f600', 30), null::text,
          U&'display: U+00A8 then joiner and emoji');
select is(public.name_shape(U&'a\00a9b', 30), U&'a\00a9b',
          U&'display: U+00A9 between letters');
select is(public.name_shape(U&'\00a9\fe0f', 30), U&'\00a9\fe0f',
          U&'display: U+00A9 then emoji style');
select is(public.name_shape(U&'\00a9\200d\+01f600', 30), U&'\00a9\200d\+01f600',
          U&'display: U+00A9 then joiner and emoji');
select is(public.name_shape(U&'a\00aab', 30), U&'a\00aab',
          U&'display: U+00AA between letters');
select is(public.name_shape(U&'\00aa\fe0f', 30), null::text,
          U&'display: U+00AA then emoji style');
select is(public.name_shape(U&'\00aa\200d\+01f600', 30), null::text,
          U&'display: U+00AA then joiner and emoji');
select is(public.name_shape(U&'a\00acb', 30), U&'a\00acb',
          U&'display: U+00AC between letters');
select is(public.name_shape(U&'\00ac\fe0f', 30), null::text,
          U&'display: U+00AC then emoji style');
select is(public.name_shape(U&'\00ac\200d\+01f600', 30), null::text,
          U&'display: U+00AC then joiner and emoji');
select is(public.name_shape(U&'a\00adb', 30), null::text,
          U&'display: U+00AD between letters');
select is(public.name_shape(U&'\00ad\fe0f', 30), null::text,
          U&'display: U+00AD then emoji style');
select is(public.name_shape(U&'\00ad\200d\+01f600', 30), null::text,
          U&'display: U+00AD then joiner and emoji');
select is(public.name_shape(U&'a\00aeb', 30), U&'a\00aeb',
          U&'display: U+00AE between letters');
select is(public.name_shape(U&'\00ae\fe0f', 30), U&'\00ae\fe0f',
          U&'display: U+00AE then emoji style');
select is(public.name_shape(U&'\00ae\200d\+01f600', 30), U&'\00ae\200d\+01f600',
          U&'display: U+00AE then joiner and emoji');
select is(public.name_shape(U&'a\00afb', 30), U&'a\00afb',
          U&'display: U+00AF between letters');
select is(public.name_shape(U&'\00af\fe0f', 30), null::text,
          U&'display: U+00AF then emoji style');
select is(public.name_shape(U&'\00af\200d\+01f600', 30), null::text,
          U&'display: U+00AF then joiner and emoji');
select is(public.name_shape(U&'a\034eb', 30), U&'a\034eb',
          U&'display: U+034E between letters');
select is(public.name_shape(U&'\034e\fe0f', 30), null::text,
          U&'display: U+034E then emoji style');
select is(public.name_shape(U&'\034e\200d\+01f600', 30), null::text,
          U&'display: U+034E then joiner and emoji');
select is(public.name_shape(U&'a\034fb', 30), null::text,
          U&'display: U+034F between letters');
select is(public.name_shape(U&'\034f\fe0f', 30), null::text,
          U&'display: U+034F then emoji style');
select is(public.name_shape(U&'\034f\200d\+01f600', 30), null::text,
          U&'display: U+034F then joiner and emoji');
select is(public.name_shape(U&'a\0350b', 30), U&'a\0350b',
          U&'display: U+0350 between letters');
select is(public.name_shape(U&'\0350\fe0f', 30), null::text,
          U&'display: U+0350 then emoji style');
select is(public.name_shape(U&'\0350\200d\+01f600', 30), null::text,
          U&'display: U+0350 then joiner and emoji');
select is(public.name_shape(U&'a\05ffb', 30), U&'a\05ffb',
          U&'display: U+05FF between letters');
select is(public.name_shape(U&'\05ff\fe0f', 30), null::text,
          U&'display: U+05FF then emoji style');
select is(public.name_shape(U&'\05ff\200d\+01f600', 30), null::text,
          U&'display: U+05FF then joiner and emoji');
select is(public.name_shape(U&'a\0600b', 30), null::text,
          U&'display: U+0600 between letters');
select is(public.name_shape(U&'\0600\fe0f', 30), null::text,
          U&'display: U+0600 then emoji style');
select is(public.name_shape(U&'\0600\200d\+01f600', 30), null::text,
          U&'display: U+0600 then joiner and emoji');
select is(public.name_shape(U&'a\0605b', 30), null::text,
          U&'display: U+0605 between letters');
select is(public.name_shape(U&'\0605\fe0f', 30), null::text,
          U&'display: U+0605 then emoji style');
select is(public.name_shape(U&'\0605\200d\+01f600', 30), null::text,
          U&'display: U+0605 then joiner and emoji');
select is(public.name_shape(U&'a\0606b', 30), U&'a\0606b',
          U&'display: U+0606 between letters');
select is(public.name_shape(U&'\0606\fe0f', 30), null::text,
          U&'display: U+0606 then emoji style');
select is(public.name_shape(U&'\0606\200d\+01f600', 30), null::text,
          U&'display: U+0606 then joiner and emoji');
select is(public.name_shape(U&'a\061bb', 30), U&'a\061bb',
          U&'display: U+061B between letters');
select is(public.name_shape(U&'\061b\fe0f', 30), null::text,
          U&'display: U+061B then emoji style');
select is(public.name_shape(U&'\061b\200d\+01f600', 30), null::text,
          U&'display: U+061B then joiner and emoji');
select is(public.name_shape(U&'a\061cb', 30), null::text,
          U&'display: U+061C between letters');
select is(public.name_shape(U&'\061c\fe0f', 30), null::text,
          U&'display: U+061C then emoji style');
select is(public.name_shape(U&'\061c\200d\+01f600', 30), null::text,
          U&'display: U+061C then joiner and emoji');
select is(public.name_shape(U&'a\061db', 30), U&'a\061db',
          U&'display: U+061D between letters');
select is(public.name_shape(U&'\061d\fe0f', 30), null::text,
          U&'display: U+061D then emoji style');
select is(public.name_shape(U&'\061d\200d\+01f600', 30), null::text,
          U&'display: U+061D then joiner and emoji');
select is(public.name_shape(U&'a\06dcb', 30), U&'a\06dcb',
          U&'display: U+06DC between letters');
select is(public.name_shape(U&'\06dc\fe0f', 30), null::text,
          U&'display: U+06DC then emoji style');
select is(public.name_shape(U&'\06dc\200d\+01f600', 30), null::text,
          U&'display: U+06DC then joiner and emoji');
select is(public.name_shape(U&'a\06ddb', 30), null::text,
          U&'display: U+06DD between letters');
select is(public.name_shape(U&'\06dd\fe0f', 30), null::text,
          U&'display: U+06DD then emoji style');
select is(public.name_shape(U&'\06dd\200d\+01f600', 30), null::text,
          U&'display: U+06DD then joiner and emoji');
select is(public.name_shape(U&'a\06deb', 30), U&'a\06deb',
          U&'display: U+06DE between letters');
select is(public.name_shape(U&'\06de\fe0f', 30), null::text,
          U&'display: U+06DE then emoji style');
select is(public.name_shape(U&'\06de\200d\+01f600', 30), null::text,
          U&'display: U+06DE then joiner and emoji');
select is(public.name_shape(U&'a\070eb', 30), U&'a\070eb',
          U&'display: U+070E between letters');
select is(public.name_shape(U&'\070e\fe0f', 30), null::text,
          U&'display: U+070E then emoji style');
select is(public.name_shape(U&'\070e\200d\+01f600', 30), null::text,
          U&'display: U+070E then joiner and emoji');
select is(public.name_shape(U&'a\070fb', 30), null::text,
          U&'display: U+070F between letters');
select is(public.name_shape(U&'\070f\fe0f', 30), null::text,
          U&'display: U+070F then emoji style');
select is(public.name_shape(U&'\070f\200d\+01f600', 30), null::text,
          U&'display: U+070F then joiner and emoji');
select is(public.name_shape(U&'a\0710b', 30), U&'a\0710b',
          U&'display: U+0710 between letters');
select is(public.name_shape(U&'\0710\fe0f', 30), null::text,
          U&'display: U+0710 then emoji style');
select is(public.name_shape(U&'\0710\200d\+01f600', 30), null::text,
          U&'display: U+0710 then joiner and emoji');
select is(public.name_shape(U&'a\088fb', 30), U&'a\088fb',
          U&'display: U+088F between letters');
select is(public.name_shape(U&'\088f\fe0f', 30), null::text,
          U&'display: U+088F then emoji style');
select is(public.name_shape(U&'\088f\200d\+01f600', 30), null::text,
          U&'display: U+088F then joiner and emoji');
select is(public.name_shape(U&'a\0890b', 30), null::text,
          U&'display: U+0890 between letters');
select is(public.name_shape(U&'\0890\fe0f', 30), null::text,
          U&'display: U+0890 then emoji style');
select is(public.name_shape(U&'\0890\200d\+01f600', 30), null::text,
          U&'display: U+0890 then joiner and emoji');
select is(public.name_shape(U&'a\0891b', 30), null::text,
          U&'display: U+0891 between letters');
select is(public.name_shape(U&'\0891\fe0f', 30), null::text,
          U&'display: U+0891 then emoji style');
select is(public.name_shape(U&'\0891\200d\+01f600', 30), null::text,
          U&'display: U+0891 then joiner and emoji');
select is(public.name_shape(U&'a\0892b', 30), U&'a\0892b',
          U&'display: U+0892 between letters');
select is(public.name_shape(U&'\0892\fe0f', 30), null::text,
          U&'display: U+0892 then emoji style');
select is(public.name_shape(U&'\0892\200d\+01f600', 30), null::text,
          U&'display: U+0892 then joiner and emoji');
select is(public.name_shape(U&'a\08e1b', 30), U&'a\08e1b',
          U&'display: U+08E1 between letters');
select is(public.name_shape(U&'\08e1\fe0f', 30), null::text,
          U&'display: U+08E1 then emoji style');
select is(public.name_shape(U&'\08e1\200d\+01f600', 30), null::text,
          U&'display: U+08E1 then joiner and emoji');
select is(public.name_shape(U&'a\08e2b', 30), null::text,
          U&'display: U+08E2 between letters');
select is(public.name_shape(U&'\08e2\fe0f', 30), null::text,
          U&'display: U+08E2 then emoji style');
select is(public.name_shape(U&'\08e2\200d\+01f600', 30), null::text,
          U&'display: U+08E2 then joiner and emoji');
select is(public.name_shape(U&'a\08e3b', 30), U&'a\08e3b',
          U&'display: U+08E3 between letters');
select is(public.name_shape(U&'\08e3\fe0f', 30), null::text,
          U&'display: U+08E3 then emoji style');
select is(public.name_shape(U&'\08e3\200d\+01f600', 30), null::text,
          U&'display: U+08E3 then joiner and emoji');
select is(public.name_shape(U&'a\115eb', 30), U&'a\115eb',
          U&'display: U+115E between letters');
select is(public.name_shape(U&'\115e\fe0f', 30), null::text,
          U&'display: U+115E then emoji style');
select is(public.name_shape(U&'\115e\200d\+01f600', 30), null::text,
          U&'display: U+115E then joiner and emoji');
select is(public.name_shape(U&'a\115fb', 30), null::text,
          U&'display: U+115F between letters');
select is(public.name_shape(U&'\115f\fe0f', 30), null::text,
          U&'display: U+115F then emoji style');
select is(public.name_shape(U&'\115f\200d\+01f600', 30), null::text,
          U&'display: U+115F then joiner and emoji');
select is(public.name_shape(U&'a\1160b', 30), null::text,
          U&'display: U+1160 between letters');
select is(public.name_shape(U&'\1160\fe0f', 30), null::text,
          U&'display: U+1160 then emoji style');
select is(public.name_shape(U&'\1160\200d\+01f600', 30), null::text,
          U&'display: U+1160 then joiner and emoji');
select is(public.name_shape(U&'a\1161b', 30), U&'a\1161b',
          U&'display: U+1161 between letters');
select is(public.name_shape(U&'\1161\fe0f', 30), null::text,
          U&'display: U+1161 then emoji style');
select is(public.name_shape(U&'\1161\200d\+01f600', 30), null::text,
          U&'display: U+1161 then joiner and emoji');
select is(public.name_shape(U&'a\167fb', 30), U&'a\167fb',
          U&'display: U+167F between letters');
select is(public.name_shape(U&'\167f\fe0f', 30), null::text,
          U&'display: U+167F then emoji style');
select is(public.name_shape(U&'\167f\200d\+01f600', 30), null::text,
          U&'display: U+167F then joiner and emoji');
select is(public.name_shape(U&'a\1680b', 30), U&'a b',
          U&'display: U+1680 between letters');
select is(public.name_shape(U&'\1680\fe0f', 30), null::text,
          U&'display: U+1680 then emoji style');
select is(public.name_shape(U&'\1680\200d\+01f600', 30), null::text,
          U&'display: U+1680 then joiner and emoji');
select is(public.name_shape(U&'a\1681b', 30), U&'a\1681b',
          U&'display: U+1681 between letters');
select is(public.name_shape(U&'\1681\fe0f', 30), null::text,
          U&'display: U+1681 then emoji style');
select is(public.name_shape(U&'\1681\200d\+01f600', 30), null::text,
          U&'display: U+1681 then joiner and emoji');
select is(public.name_shape(U&'a\17b3b', 30), U&'a\17b3b',
          U&'display: U+17B3 between letters');
select is(public.name_shape(U&'\17b3\fe0f', 30), null::text,
          U&'display: U+17B3 then emoji style');
select is(public.name_shape(U&'\17b3\200d\+01f600', 30), null::text,
          U&'display: U+17B3 then joiner and emoji');
select is(public.name_shape(U&'a\17b4b', 30), null::text,
          U&'display: U+17B4 between letters');
select is(public.name_shape(U&'\17b4\fe0f', 30), null::text,
          U&'display: U+17B4 then emoji style');
select is(public.name_shape(U&'\17b4\200d\+01f600', 30), null::text,
          U&'display: U+17B4 then joiner and emoji');
select is(public.name_shape(U&'a\17b5b', 30), null::text,
          U&'display: U+17B5 between letters');
select is(public.name_shape(U&'\17b5\fe0f', 30), null::text,
          U&'display: U+17B5 then emoji style');
select is(public.name_shape(U&'\17b5\200d\+01f600', 30), null::text,
          U&'display: U+17B5 then joiner and emoji');
select is(public.name_shape(U&'a\17b6b', 30), U&'a\17b6b',
          U&'display: U+17B6 between letters');
select is(public.name_shape(U&'\17b6\fe0f', 30), null::text,
          U&'display: U+17B6 then emoji style');
select is(public.name_shape(U&'\17b6\200d\+01f600', 30), null::text,
          U&'display: U+17B6 then joiner and emoji');
select is(public.name_shape(U&'a\180ab', 30), U&'a\180ab',
          U&'display: U+180A between letters');
select is(public.name_shape(U&'\180a\fe0f', 30), null::text,
          U&'display: U+180A then emoji style');
select is(public.name_shape(U&'\180a\200d\+01f600', 30), null::text,
          U&'display: U+180A then joiner and emoji');
select is(public.name_shape(U&'a\180bb', 30), null::text,
          U&'display: U+180B between letters');
select is(public.name_shape(U&'\180b\fe0f', 30), null::text,
          U&'display: U+180B then emoji style');
select is(public.name_shape(U&'\180b\200d\+01f600', 30), null::text,
          U&'display: U+180B then joiner and emoji');
select is(public.name_shape(U&'a\180fb', 30), null::text,
          U&'display: U+180F between letters');
select is(public.name_shape(U&'\180f\fe0f', 30), null::text,
          U&'display: U+180F then emoji style');
select is(public.name_shape(U&'\180f\200d\+01f600', 30), null::text,
          U&'display: U+180F then joiner and emoji');
select is(public.name_shape(U&'a\1810b', 30), U&'a\1810b',
          U&'display: U+1810 between letters');
select is(public.name_shape(U&'\1810\fe0f', 30), null::text,
          U&'display: U+1810 then emoji style');
select is(public.name_shape(U&'\1810\200d\+01f600', 30), null::text,
          U&'display: U+1810 then joiner and emoji');
select is(public.name_shape(U&'a\1fffb', 30), U&'a\1fffb',
          U&'display: U+1FFF between letters');
select is(public.name_shape(U&'\1fff\fe0f', 30), null::text,
          U&'display: U+1FFF then emoji style');
select is(public.name_shape(U&'\1fff\200d\+01f600', 30), null::text,
          U&'display: U+1FFF then joiner and emoji');
select is(public.name_shape(U&'a\2000b', 30), U&'a b',
          U&'display: U+2000 between letters');
select is(public.name_shape(U&'\2000\fe0f', 30), null::text,
          U&'display: U+2000 then emoji style');
select is(public.name_shape(U&'\2000\200d\+01f600', 30), null::text,
          U&'display: U+2000 then joiner and emoji');
select is(public.name_shape(U&'a\200ab', 30), U&'a b',
          U&'display: U+200A between letters');
select is(public.name_shape(U&'\200a\fe0f', 30), null::text,
          U&'display: U+200A then emoji style');
select is(public.name_shape(U&'\200a\200d\+01f600', 30), null::text,
          U&'display: U+200A then joiner and emoji');
select is(public.name_shape(U&'a\200bb', 30), null::text,
          U&'display: U+200B between letters');
select is(public.name_shape(U&'\200b\fe0f', 30), null::text,
          U&'display: U+200B then emoji style');
select is(public.name_shape(U&'\200b\200d\+01f600', 30), null::text,
          U&'display: U+200B then joiner and emoji');
select is(public.name_shape(U&'a\200cb', 30), null::text,
          U&'display: U+200C between letters');
select is(public.name_shape(U&'\200c\fe0f', 30), null::text,
          U&'display: U+200C then emoji style');
select is(public.name_shape(U&'\200c\200d\+01f600', 30), null::text,
          U&'display: U+200C then joiner and emoji');
select is(public.name_shape(U&'a\200db', 30), null::text,
          U&'display: U+200D between letters');
select is(public.name_shape(U&'\200d\fe0f', 30), null::text,
          U&'display: U+200D then emoji style');
select is(public.name_shape(U&'\200d\200d\+01f600', 30), null::text,
          U&'display: U+200D then joiner and emoji');
select is(public.name_shape(U&'a\200eb', 30), null::text,
          U&'display: U+200E between letters');
select is(public.name_shape(U&'\200e\fe0f', 30), null::text,
          U&'display: U+200E then emoji style');
select is(public.name_shape(U&'\200e\200d\+01f600', 30), null::text,
          U&'display: U+200E then joiner and emoji');
select is(public.name_shape(U&'a\200fb', 30), null::text,
          U&'display: U+200F between letters');
select is(public.name_shape(U&'\200f\fe0f', 30), null::text,
          U&'display: U+200F then emoji style');
select is(public.name_shape(U&'\200f\200d\+01f600', 30), null::text,
          U&'display: U+200F then joiner and emoji');
select is(public.name_shape(U&'a\2010b', 30), U&'a\2010b',
          U&'display: U+2010 between letters');
select is(public.name_shape(U&'\2010\fe0f', 30), null::text,
          U&'display: U+2010 then emoji style');
select is(public.name_shape(U&'\2010\200d\+01f600', 30), null::text,
          U&'display: U+2010 then joiner and emoji');
select is(public.name_shape(U&'a\2027b', 30), U&'a\2027b',
          U&'display: U+2027 between letters');
select is(public.name_shape(U&'\2027\fe0f', 30), null::text,
          U&'display: U+2027 then emoji style');
select is(public.name_shape(U&'\2027\200d\+01f600', 30), null::text,
          U&'display: U+2027 then joiner and emoji');
select is(public.name_shape(U&'a\2028b', 30), null::text,
          U&'display: U+2028 between letters');
select is(public.name_shape(U&'\2028\fe0f', 30), null::text,
          U&'display: U+2028 then emoji style');
select is(public.name_shape(U&'\2028\200d\+01f600', 30), null::text,
          U&'display: U+2028 then joiner and emoji');
select is(public.name_shape(U&'a\202eb', 30), null::text,
          U&'display: U+202E between letters');
select is(public.name_shape(U&'\202e\fe0f', 30), null::text,
          U&'display: U+202E then emoji style');
select is(public.name_shape(U&'\202e\200d\+01f600', 30), null::text,
          U&'display: U+202E then joiner and emoji');
select is(public.name_shape(U&'a\202fb', 30), U&'a b',
          U&'display: U+202F between letters');
select is(public.name_shape(U&'\202f\fe0f', 30), null::text,
          U&'display: U+202F then emoji style');
select is(public.name_shape(U&'\202f\200d\+01f600', 30), null::text,
          U&'display: U+202F then joiner and emoji');
select is(public.name_shape(U&'a\2030b', 30), U&'a\2030b',
          U&'display: U+2030 between letters');
select is(public.name_shape(U&'\2030\fe0f', 30), null::text,
          U&'display: U+2030 then emoji style');
select is(public.name_shape(U&'\2030\200d\+01f600', 30), null::text,
          U&'display: U+2030 then joiner and emoji');
select is(public.name_shape(U&'a\203bb', 30), U&'a\203bb',
          U&'display: U+203B between letters');
select is(public.name_shape(U&'\203b\fe0f', 30), null::text,
          U&'display: U+203B then emoji style');
select is(public.name_shape(U&'\203b\200d\+01f600', 30), null::text,
          U&'display: U+203B then joiner and emoji');
select is(public.name_shape(U&'a\203cb', 30), U&'a\203cb',
          U&'display: U+203C between letters');
select is(public.name_shape(U&'\203c\fe0f', 30), U&'\203c\fe0f',
          U&'display: U+203C then emoji style');
select is(public.name_shape(U&'\203c\200d\+01f600', 30), U&'\203c\200d\+01f600',
          U&'display: U+203C then joiner and emoji');
select is(public.name_shape(U&'a\203db', 30), U&'a\203db',
          U&'display: U+203D between letters');
select is(public.name_shape(U&'\203d\fe0f', 30), null::text,
          U&'display: U+203D then emoji style');
select is(public.name_shape(U&'\203d\200d\+01f600', 30), null::text,
          U&'display: U+203D then joiner and emoji');
select is(public.name_shape(U&'a\2048b', 30), U&'a\2048b',
          U&'display: U+2048 between letters');
select is(public.name_shape(U&'\2048\fe0f', 30), null::text,
          U&'display: U+2048 then emoji style');
select is(public.name_shape(U&'\2048\200d\+01f600', 30), null::text,
          U&'display: U+2048 then joiner and emoji');
select is(public.name_shape(U&'a\2049b', 30), U&'a\2049b',
          U&'display: U+2049 between letters');
select is(public.name_shape(U&'\2049\fe0f', 30), U&'\2049\fe0f',
          U&'display: U+2049 then emoji style');
select is(public.name_shape(U&'\2049\200d\+01f600', 30), U&'\2049\200d\+01f600',
          U&'display: U+2049 then joiner and emoji');
select is(public.name_shape(U&'a\204ab', 30), U&'a\204ab',
          U&'display: U+204A between letters');
select is(public.name_shape(U&'\204a\fe0f', 30), null::text,
          U&'display: U+204A then emoji style');
select is(public.name_shape(U&'\204a\200d\+01f600', 30), null::text,
          U&'display: U+204A then joiner and emoji');
select is(public.name_shape(U&'a\205eb', 30), U&'a\205eb',
          U&'display: U+205E between letters');
select is(public.name_shape(U&'\205e\fe0f', 30), null::text,
          U&'display: U+205E then emoji style');
select is(public.name_shape(U&'\205e\200d\+01f600', 30), null::text,
          U&'display: U+205E then joiner and emoji');
select is(public.name_shape(U&'a\205fb', 30), U&'a b',
          U&'display: U+205F between letters');
select is(public.name_shape(U&'\205f\fe0f', 30), null::text,
          U&'display: U+205F then emoji style');
select is(public.name_shape(U&'\205f\200d\+01f600', 30), null::text,
          U&'display: U+205F then joiner and emoji');
select is(public.name_shape(U&'a\2060b', 30), null::text,
          U&'display: U+2060 between letters');
select is(public.name_shape(U&'\2060\fe0f', 30), null::text,
          U&'display: U+2060 then emoji style');
select is(public.name_shape(U&'\2060\200d\+01f600', 30), null::text,
          U&'display: U+2060 then joiner and emoji');
select is(public.name_shape(U&'a\206fb', 30), null::text,
          U&'display: U+206F between letters');
select is(public.name_shape(U&'\206f\fe0f', 30), null::text,
          U&'display: U+206F then emoji style');
select is(public.name_shape(U&'\206f\200d\+01f600', 30), null::text,
          U&'display: U+206F then joiner and emoji');
select is(public.name_shape(U&'a\2070b', 30), U&'a\2070b',
          U&'display: U+2070 between letters');
select is(public.name_shape(U&'\2070\fe0f', 30), null::text,
          U&'display: U+2070 then emoji style');
select is(public.name_shape(U&'\2070\200d\+01f600', 30), null::text,
          U&'display: U+2070 then joiner and emoji');
select is(public.name_shape(U&'a\2121b', 30), U&'a\2121b',
          U&'display: U+2121 between letters');
select is(public.name_shape(U&'\2121\fe0f', 30), null::text,
          U&'display: U+2121 then emoji style');
select is(public.name_shape(U&'\2121\200d\+01f600', 30), null::text,
          U&'display: U+2121 then joiner and emoji');
select is(public.name_shape(U&'a\2122b', 30), U&'a\2122b',
          U&'display: U+2122 between letters');
select is(public.name_shape(U&'\2122\fe0f', 30), U&'\2122\fe0f',
          U&'display: U+2122 then emoji style');
select is(public.name_shape(U&'\2122\200d\+01f600', 30), U&'\2122\200d\+01f600',
          U&'display: U+2122 then joiner and emoji');
select is(public.name_shape(U&'a\2123b', 30), U&'a\2123b',
          U&'display: U+2123 between letters');
select is(public.name_shape(U&'\2123\fe0f', 30), null::text,
          U&'display: U+2123 then emoji style');
select is(public.name_shape(U&'\2123\200d\+01f600', 30), null::text,
          U&'display: U+2123 then joiner and emoji');
select is(public.name_shape(U&'a\2138b', 30), U&'a\2138b',
          U&'display: U+2138 between letters');
select is(public.name_shape(U&'\2138\fe0f', 30), null::text,
          U&'display: U+2138 then emoji style');
select is(public.name_shape(U&'\2138\200d\+01f600', 30), null::text,
          U&'display: U+2138 then joiner and emoji');
select is(public.name_shape(U&'a\2139b', 30), U&'a\2139b',
          U&'display: U+2139 between letters');
select is(public.name_shape(U&'\2139\fe0f', 30), U&'\2139\fe0f',
          U&'display: U+2139 then emoji style');
select is(public.name_shape(U&'\2139\200d\+01f600', 30), U&'\2139\200d\+01f600',
          U&'display: U+2139 then joiner and emoji');
select is(public.name_shape(U&'a\213ab', 30), U&'a\213ab',
          U&'display: U+213A between letters');
select is(public.name_shape(U&'\213a\fe0f', 30), null::text,
          U&'display: U+213A then emoji style');
select is(public.name_shape(U&'\213a\200d\+01f600', 30), null::text,
          U&'display: U+213A then joiner and emoji');
select is(public.name_shape(U&'a\2193b', 30), U&'a\2193b',
          U&'display: U+2193 between letters');
select is(public.name_shape(U&'\2193\fe0f', 30), null::text,
          U&'display: U+2193 then emoji style');
select is(public.name_shape(U&'\2193\200d\+01f600', 30), null::text,
          U&'display: U+2193 then joiner and emoji');
select is(public.name_shape(U&'a\2194b', 30), U&'a\2194b',
          U&'display: U+2194 between letters');
select is(public.name_shape(U&'\2194\fe0f', 30), U&'\2194\fe0f',
          U&'display: U+2194 then emoji style');
select is(public.name_shape(U&'\2194\200d\+01f600', 30), U&'\2194\200d\+01f600',
          U&'display: U+2194 then joiner and emoji');
select is(public.name_shape(U&'a\21aab', 30), U&'a\21aab',
          U&'display: U+21AA between letters');
select is(public.name_shape(U&'\21aa\fe0f', 30), U&'\21aa\fe0f',
          U&'display: U+21AA then emoji style');
select is(public.name_shape(U&'\21aa\200d\+01f600', 30), U&'\21aa\200d\+01f600',
          U&'display: U+21AA then joiner and emoji');
select is(public.name_shape(U&'a\21abb', 30), U&'a\21abb',
          U&'display: U+21AB between letters');
select is(public.name_shape(U&'\21ab\fe0f', 30), null::text,
          U&'display: U+21AB then emoji style');
select is(public.name_shape(U&'\21ab\200d\+01f600', 30), null::text,
          U&'display: U+21AB then joiner and emoji');
select is(public.name_shape(U&'a\2319b', 30), U&'a\2319b',
          U&'display: U+2319 between letters');
select is(public.name_shape(U&'\2319\fe0f', 30), null::text,
          U&'display: U+2319 then emoji style');
select is(public.name_shape(U&'\2319\200d\+01f600', 30), null::text,
          U&'display: U+2319 then joiner and emoji');
select is(public.name_shape(U&'a\231ab', 30), U&'a\231ab',
          U&'display: U+231A between letters');
select is(public.name_shape(U&'\231a\fe0f', 30), U&'\231a\fe0f',
          U&'display: U+231A then emoji style');
select is(public.name_shape(U&'\231a\200d\+01f600', 30), U&'\231a\200d\+01f600',
          U&'display: U+231A then joiner and emoji');
select is(public.name_shape(U&'a\23ffb', 30), U&'a\23ffb',
          U&'display: U+23FF between letters');
select is(public.name_shape(U&'\23ff\fe0f', 30), U&'\23ff\fe0f',
          U&'display: U+23FF then emoji style');
select is(public.name_shape(U&'\23ff\200d\+01f600', 30), U&'\23ff\200d\+01f600',
          U&'display: U+23FF then joiner and emoji');
select is(public.name_shape(U&'a\2400b', 30), U&'a\2400b',
          U&'display: U+2400 between letters');
select is(public.name_shape(U&'\2400\fe0f', 30), null::text,
          U&'display: U+2400 then emoji style');
select is(public.name_shape(U&'\2400\200d\+01f600', 30), null::text,
          U&'display: U+2400 then joiner and emoji');
select is(public.name_shape(U&'a\24c1b', 30), U&'a\24c1b',
          U&'display: U+24C1 between letters');
select is(public.name_shape(U&'\24c1\fe0f', 30), null::text,
          U&'display: U+24C1 then emoji style');
select is(public.name_shape(U&'\24c1\200d\+01f600', 30), null::text,
          U&'display: U+24C1 then joiner and emoji');
select is(public.name_shape(U&'a\24c2b', 30), U&'a\24c2b',
          U&'display: U+24C2 between letters');
select is(public.name_shape(U&'\24c2\fe0f', 30), U&'\24c2\fe0f',
          U&'display: U+24C2 then emoji style');
select is(public.name_shape(U&'\24c2\200d\+01f600', 30), U&'\24c2\200d\+01f600',
          U&'display: U+24C2 then joiner and emoji');
select is(public.name_shape(U&'a\24c3b', 30), U&'a\24c3b',
          U&'display: U+24C3 between letters');
select is(public.name_shape(U&'\24c3\fe0f', 30), null::text,
          U&'display: U+24C3 then emoji style');
select is(public.name_shape(U&'\24c3\200d\+01f600', 30), null::text,
          U&'display: U+24C3 then joiner and emoji');
select is(public.name_shape(U&'a\25a9b', 30), U&'a\25a9b',
          U&'display: U+25A9 between letters');
select is(public.name_shape(U&'\25a9\fe0f', 30), null::text,
          U&'display: U+25A9 then emoji style');
select is(public.name_shape(U&'\25a9\200d\+01f600', 30), null::text,
          U&'display: U+25A9 then joiner and emoji');
select is(public.name_shape(U&'a\25aab', 30), U&'a\25aab',
          U&'display: U+25AA between letters');
select is(public.name_shape(U&'\25aa\fe0f', 30), U&'\25aa\fe0f',
          U&'display: U+25AA then emoji style');
select is(public.name_shape(U&'\25aa\200d\+01f600', 30), U&'\25aa\200d\+01f600',
          U&'display: U+25AA then joiner and emoji');
select is(public.name_shape(U&'a\25feb', 30), U&'a\25feb',
          U&'display: U+25FE between letters');
select is(public.name_shape(U&'\25fe\fe0f', 30), U&'\25fe\fe0f',
          U&'display: U+25FE then emoji style');
select is(public.name_shape(U&'\25fe\200d\+01f600', 30), U&'\25fe\200d\+01f600',
          U&'display: U+25FE then joiner and emoji');
select is(public.name_shape(U&'a\25ffb', 30), U&'a\25ffb',
          U&'display: U+25FF between letters');
select is(public.name_shape(U&'\25ff\fe0f', 30), null::text,
          U&'display: U+25FF then emoji style');
select is(public.name_shape(U&'\25ff\200d\+01f600', 30), null::text,
          U&'display: U+25FF then joiner and emoji');
select is(public.name_shape(U&'a\2600b', 30), U&'a\2600b',
          U&'display: U+2600 between letters');
select is(public.name_shape(U&'\2600\fe0f', 30), U&'\2600\fe0f',
          U&'display: U+2600 then emoji style');
select is(public.name_shape(U&'\2600\200d\+01f600', 30), U&'\2600\200d\+01f600',
          U&'display: U+2600 then joiner and emoji');
select is(public.name_shape(U&'a\27bfb', 30), U&'a\27bfb',
          U&'display: U+27BF between letters');
select is(public.name_shape(U&'\27bf\fe0f', 30), U&'\27bf\fe0f',
          U&'display: U+27BF then emoji style');
select is(public.name_shape(U&'\27bf\200d\+01f600', 30), U&'\27bf\200d\+01f600',
          U&'display: U+27BF then joiner and emoji');
select is(public.name_shape(U&'a\27c0b', 30), U&'a\27c0b',
          U&'display: U+27C0 between letters');
select is(public.name_shape(U&'\27c0\fe0f', 30), null::text,
          U&'display: U+27C0 then emoji style');
select is(public.name_shape(U&'\27c0\200d\+01f600', 30), null::text,
          U&'display: U+27C0 then joiner and emoji');
select is(public.name_shape(U&'a\27ffb', 30), U&'a\27ffb',
          U&'display: U+27FF between letters');
select is(public.name_shape(U&'\27ff\fe0f', 30), null::text,
          U&'display: U+27FF then emoji style');
select is(public.name_shape(U&'\27ff\200d\+01f600', 30), null::text,
          U&'display: U+27FF then joiner and emoji');
select is(public.name_shape(U&'a\2800b', 30), null::text,
          U&'display: U+2800 between letters');
select is(public.name_shape(U&'\2800\fe0f', 30), null::text,
          U&'display: U+2800 then emoji style');
select is(public.name_shape(U&'\2800\200d\+01f600', 30), null::text,
          U&'display: U+2800 then joiner and emoji');
select is(public.name_shape(U&'a\2801b', 30), U&'a\2801b',
          U&'display: U+2801 between letters');
select is(public.name_shape(U&'\2801\fe0f', 30), null::text,
          U&'display: U+2801 then emoji style');
select is(public.name_shape(U&'\2801\200d\+01f600', 30), null::text,
          U&'display: U+2801 then joiner and emoji');
select is(public.name_shape(U&'a\2933b', 30), U&'a\2933b',
          U&'display: U+2933 between letters');
select is(public.name_shape(U&'\2933\fe0f', 30), null::text,
          U&'display: U+2933 then emoji style');
select is(public.name_shape(U&'\2933\200d\+01f600', 30), null::text,
          U&'display: U+2933 then joiner and emoji');
select is(public.name_shape(U&'a\2934b', 30), U&'a\2934b',
          U&'display: U+2934 between letters');
select is(public.name_shape(U&'\2934\fe0f', 30), U&'\2934\fe0f',
          U&'display: U+2934 then emoji style');
select is(public.name_shape(U&'\2934\200d\+01f600', 30), U&'\2934\200d\+01f600',
          U&'display: U+2934 then joiner and emoji');
select is(public.name_shape(U&'a\2935b', 30), U&'a\2935b',
          U&'display: U+2935 between letters');
select is(public.name_shape(U&'\2935\fe0f', 30), U&'\2935\fe0f',
          U&'display: U+2935 then emoji style');
select is(public.name_shape(U&'\2935\200d\+01f600', 30), U&'\2935\200d\+01f600',
          U&'display: U+2935 then joiner and emoji');
select is(public.name_shape(U&'a\2936b', 30), U&'a\2936b',
          U&'display: U+2936 between letters');
select is(public.name_shape(U&'\2936\fe0f', 30), null::text,
          U&'display: U+2936 then emoji style');
select is(public.name_shape(U&'\2936\200d\+01f600', 30), null::text,
          U&'display: U+2936 then joiner and emoji');
select is(public.name_shape(U&'a\2b04b', 30), U&'a\2b04b',
          U&'display: U+2B04 between letters');
select is(public.name_shape(U&'\2b04\fe0f', 30), null::text,
          U&'display: U+2B04 then emoji style');
select is(public.name_shape(U&'\2b04\200d\+01f600', 30), null::text,
          U&'display: U+2B04 then joiner and emoji');
select is(public.name_shape(U&'a\2b05b', 30), U&'a\2b05b',
          U&'display: U+2B05 between letters');
select is(public.name_shape(U&'\2b05\fe0f', 30), U&'\2b05\fe0f',
          U&'display: U+2B05 then emoji style');
select is(public.name_shape(U&'\2b05\200d\+01f600', 30), U&'\2b05\200d\+01f600',
          U&'display: U+2B05 then joiner and emoji');
select is(public.name_shape(U&'a\2b55b', 30), U&'a\2b55b',
          U&'display: U+2B55 between letters');
select is(public.name_shape(U&'\2b55\fe0f', 30), U&'\2b55\fe0f',
          U&'display: U+2B55 then emoji style');
select is(public.name_shape(U&'\2b55\200d\+01f600', 30), U&'\2b55\200d\+01f600',
          U&'display: U+2B55 then joiner and emoji');
select is(public.name_shape(U&'a\2b56b', 30), U&'a\2b56b',
          U&'display: U+2B56 between letters');
select is(public.name_shape(U&'\2b56\fe0f', 30), null::text,
          U&'display: U+2B56 then emoji style');
select is(public.name_shape(U&'\2b56\200d\+01f600', 30), null::text,
          U&'display: U+2B56 then joiner and emoji');
select is(public.name_shape(U&'a\2fffb', 30), U&'a\2fffb',
          U&'display: U+2FFF between letters');
select is(public.name_shape(U&'\2fff\fe0f', 30), null::text,
          U&'display: U+2FFF then emoji style');
select is(public.name_shape(U&'\2fff\200d\+01f600', 30), null::text,
          U&'display: U+2FFF then joiner and emoji');
select is(public.name_shape(U&'a\3000b', 30), U&'a b',
          U&'display: U+3000 between letters');
select is(public.name_shape(U&'\3000\fe0f', 30), null::text,
          U&'display: U+3000 then emoji style');
select is(public.name_shape(U&'\3000\200d\+01f600', 30), null::text,
          U&'display: U+3000 then joiner and emoji');
select is(public.name_shape(U&'a\3001b', 30), U&'a\3001b',
          U&'display: U+3001 between letters');
select is(public.name_shape(U&'\3001\fe0f', 30), null::text,
          U&'display: U+3001 then emoji style');
select is(public.name_shape(U&'\3001\200d\+01f600', 30), null::text,
          U&'display: U+3001 then joiner and emoji');
select is(public.name_shape(U&'a\302fb', 30), U&'a\302fb',
          U&'display: U+302F between letters');
select is(public.name_shape(U&'\302f\fe0f', 30), null::text,
          U&'display: U+302F then emoji style');
select is(public.name_shape(U&'\302f\200d\+01f600', 30), null::text,
          U&'display: U+302F then joiner and emoji');
select is(public.name_shape(U&'a\3030b', 30), U&'a\3030b',
          U&'display: U+3030 between letters');
select is(public.name_shape(U&'\3030\fe0f', 30), U&'\3030\fe0f',
          U&'display: U+3030 then emoji style');
select is(public.name_shape(U&'\3030\200d\+01f600', 30), U&'\3030\200d\+01f600',
          U&'display: U+3030 then joiner and emoji');
select is(public.name_shape(U&'a\3031b', 30), U&'a\3031b',
          U&'display: U+3031 between letters');
select is(public.name_shape(U&'\3031\fe0f', 30), null::text,
          U&'display: U+3031 then emoji style');
select is(public.name_shape(U&'\3031\200d\+01f600', 30), null::text,
          U&'display: U+3031 then joiner and emoji');
select is(public.name_shape(U&'a\303cb', 30), U&'a\303cb',
          U&'display: U+303C between letters');
select is(public.name_shape(U&'\303c\fe0f', 30), null::text,
          U&'display: U+303C then emoji style');
select is(public.name_shape(U&'\303c\200d\+01f600', 30), null::text,
          U&'display: U+303C then joiner and emoji');
select is(public.name_shape(U&'a\303db', 30), U&'a\303db',
          U&'display: U+303D between letters');
select is(public.name_shape(U&'\303d\fe0f', 30), U&'\303d\fe0f',
          U&'display: U+303D then emoji style');
select is(public.name_shape(U&'\303d\200d\+01f600', 30), U&'\303d\200d\+01f600',
          U&'display: U+303D then joiner and emoji');
select is(public.name_shape(U&'a\303eb', 30), U&'a\303eb',
          U&'display: U+303E between letters');
select is(public.name_shape(U&'\303e\fe0f', 30), null::text,
          U&'display: U+303E then emoji style');
select is(public.name_shape(U&'\303e\200d\+01f600', 30), null::text,
          U&'display: U+303E then joiner and emoji');
select is(public.name_shape(U&'a\3163b', 30), U&'a\3163b',
          U&'display: U+3163 between letters');
select is(public.name_shape(U&'\3163\fe0f', 30), null::text,
          U&'display: U+3163 then emoji style');
select is(public.name_shape(U&'\3163\200d\+01f600', 30), null::text,
          U&'display: U+3163 then joiner and emoji');
select is(public.name_shape(U&'a\3164b', 30), null::text,
          U&'display: U+3164 between letters');
select is(public.name_shape(U&'\3164\fe0f', 30), null::text,
          U&'display: U+3164 then emoji style');
select is(public.name_shape(U&'\3164\200d\+01f600', 30), null::text,
          U&'display: U+3164 then joiner and emoji');
select is(public.name_shape(U&'a\3165b', 30), U&'a\3165b',
          U&'display: U+3165 between letters');
select is(public.name_shape(U&'\3165\fe0f', 30), null::text,
          U&'display: U+3165 then emoji style');
select is(public.name_shape(U&'\3165\200d\+01f600', 30), null::text,
          U&'display: U+3165 then joiner and emoji');
select is(public.name_shape(U&'a\3296b', 30), U&'a\3296b',
          U&'display: U+3296 between letters');
select is(public.name_shape(U&'\3296\fe0f', 30), null::text,
          U&'display: U+3296 then emoji style');
select is(public.name_shape(U&'\3296\200d\+01f600', 30), null::text,
          U&'display: U+3296 then joiner and emoji');
select is(public.name_shape(U&'a\3297b', 30), U&'a\3297b',
          U&'display: U+3297 between letters');
select is(public.name_shape(U&'\3297\fe0f', 30), U&'\3297\fe0f',
          U&'display: U+3297 then emoji style');
select is(public.name_shape(U&'\3297\200d\+01f600', 30), U&'\3297\200d\+01f600',
          U&'display: U+3297 then joiner and emoji');
select is(public.name_shape(U&'a\3298b', 30), U&'a\3298b',
          U&'display: U+3298 between letters');
select is(public.name_shape(U&'\3298\fe0f', 30), null::text,
          U&'display: U+3298 then emoji style');
select is(public.name_shape(U&'\3298\200d\+01f600', 30), null::text,
          U&'display: U+3298 then joiner and emoji');
select is(public.name_shape(U&'a\3299b', 30), U&'a\3299b',
          U&'display: U+3299 between letters');
select is(public.name_shape(U&'\3299\fe0f', 30), U&'\3299\fe0f',
          U&'display: U+3299 then emoji style');
select is(public.name_shape(U&'\3299\200d\+01f600', 30), U&'\3299\200d\+01f600',
          U&'display: U+3299 then joiner and emoji');
select is(public.name_shape(U&'a\329ab', 30), U&'a\329ab',
          U&'display: U+329A between letters');
select is(public.name_shape(U&'\329a\fe0f', 30), null::text,
          U&'display: U+329A then emoji style');
select is(public.name_shape(U&'\329a\200d\+01f600', 30), null::text,
          U&'display: U+329A then joiner and emoji');
select is(public.name_shape(U&'a\fdffb', 30), U&'a\fdffb',
          U&'display: U+FDFF between letters');
select is(public.name_shape(U&'\fdff\fe0f', 30), null::text,
          U&'display: U+FDFF then emoji style');
select is(public.name_shape(U&'\fdff\200d\+01f600', 30), null::text,
          U&'display: U+FDFF then joiner and emoji');
select is(public.name_shape(U&'a\fe00b', 30), null::text,
          U&'display: U+FE00 between letters');
select is(public.name_shape(U&'\fe00\fe0f', 30), null::text,
          U&'display: U+FE00 then emoji style');
select is(public.name_shape(U&'\fe00\200d\+01f600', 30), null::text,
          U&'display: U+FE00 then joiner and emoji');
select is(public.name_shape(U&'a\fe0eb', 30), null::text,
          U&'display: U+FE0E between letters');
select is(public.name_shape(U&'\fe0e\fe0f', 30), null::text,
          U&'display: U+FE0E then emoji style');
select is(public.name_shape(U&'\fe0e\200d\+01f600', 30), null::text,
          U&'display: U+FE0E then joiner and emoji');
select is(public.name_shape(U&'a\fe0fb', 30), null::text,
          U&'display: U+FE0F between letters');
select is(public.name_shape(U&'\fe0f\fe0f', 30), null::text,
          U&'display: U+FE0F then emoji style');
select is(public.name_shape(U&'\fe0f\200d\+01f600', 30), null::text,
          U&'display: U+FE0F then joiner and emoji');
select is(public.name_shape(U&'a\fefeb', 30), U&'a\fefeb',
          U&'display: U+FEFE between letters');
select is(public.name_shape(U&'\fefe\fe0f', 30), null::text,
          U&'display: U+FEFE then emoji style');
select is(public.name_shape(U&'\fefe\200d\+01f600', 30), null::text,
          U&'display: U+FEFE then joiner and emoji');
select is(public.name_shape(U&'a\feffb', 30), null::text,
          U&'display: U+FEFF between letters');
select is(public.name_shape(U&'\feff\fe0f', 30), null::text,
          U&'display: U+FEFF then emoji style');
select is(public.name_shape(U&'\feff\200d\+01f600', 30), null::text,
          U&'display: U+FEFF then joiner and emoji');
select is(public.name_shape(U&'a\ff00b', 30), U&'a\ff00b',
          U&'display: U+FF00 between letters');
select is(public.name_shape(U&'\ff00\fe0f', 30), null::text,
          U&'display: U+FF00 then emoji style');
select is(public.name_shape(U&'\ff00\200d\+01f600', 30), null::text,
          U&'display: U+FF00 then joiner and emoji');
select is(public.name_shape(U&'a\ff9fb', 30), U&'a\ff9fb',
          U&'display: U+FF9F between letters');
select is(public.name_shape(U&'\ff9f\fe0f', 30), null::text,
          U&'display: U+FF9F then emoji style');
select is(public.name_shape(U&'\ff9f\200d\+01f600', 30), null::text,
          U&'display: U+FF9F then joiner and emoji');
select is(public.name_shape(U&'a\ffa0b', 30), null::text,
          U&'display: U+FFA0 between letters');
select is(public.name_shape(U&'\ffa0\fe0f', 30), null::text,
          U&'display: U+FFA0 then emoji style');
select is(public.name_shape(U&'\ffa0\200d\+01f600', 30), null::text,
          U&'display: U+FFA0 then joiner and emoji');
select is(public.name_shape(U&'a\ffa1b', 30), U&'a\ffa1b',
          U&'display: U+FFA1 between letters');
select is(public.name_shape(U&'\ffa1\fe0f', 30), null::text,
          U&'display: U+FFA1 then emoji style');
select is(public.name_shape(U&'\ffa1\200d\+01f600', 30), null::text,
          U&'display: U+FFA1 then joiner and emoji');
select is(public.name_shape(U&'a\fff8b', 30), U&'a\fff8b',
          U&'display: U+FFF8 between letters');
select is(public.name_shape(U&'\fff8\fe0f', 30), null::text,
          U&'display: U+FFF8 then emoji style');
select is(public.name_shape(U&'\fff8\200d\+01f600', 30), null::text,
          U&'display: U+FFF8 then joiner and emoji');
select is(public.name_shape(U&'a\fff9b', 30), null::text,
          U&'display: U+FFF9 between letters');
select is(public.name_shape(U&'\fff9\fe0f', 30), null::text,
          U&'display: U+FFF9 then emoji style');
select is(public.name_shape(U&'\fff9\200d\+01f600', 30), null::text,
          U&'display: U+FFF9 then joiner and emoji');
select is(public.name_shape(U&'a\fffbb', 30), null::text,
          U&'display: U+FFFB between letters');
select is(public.name_shape(U&'\fffb\fe0f', 30), null::text,
          U&'display: U+FFFB then emoji style');
select is(public.name_shape(U&'\fffb\200d\+01f600', 30), null::text,
          U&'display: U+FFFB then joiner and emoji');
select is(public.name_shape(U&'a\fffcb', 30), U&'a\fffcb',
          U&'display: U+FFFC between letters');
select is(public.name_shape(U&'\fffc\fe0f', 30), null::text,
          U&'display: U+FFFC then emoji style');
select is(public.name_shape(U&'\fffc\200d\+01f600', 30), null::text,
          U&'display: U+FFFC then joiner and emoji');
select is(public.name_shape(U&'a\+0110bcb', 30), U&'a\+0110bcb',
          U&'display: U+110BC between letters');
select is(public.name_shape(U&'\+0110bc\fe0f', 30), null::text,
          U&'display: U+110BC then emoji style');
select is(public.name_shape(U&'\+0110bc\200d\+01f600', 30), null::text,
          U&'display: U+110BC then joiner and emoji');
select is(public.name_shape(U&'a\+0110bdb', 30), null::text,
          U&'display: U+110BD between letters');
select is(public.name_shape(U&'\+0110bd\fe0f', 30), null::text,
          U&'display: U+110BD then emoji style');
select is(public.name_shape(U&'\+0110bd\200d\+01f600', 30), null::text,
          U&'display: U+110BD then joiner and emoji');
select is(public.name_shape(U&'a\+0110beb', 30), U&'a\+0110beb',
          U&'display: U+110BE between letters');
select is(public.name_shape(U&'\+0110be\fe0f', 30), null::text,
          U&'display: U+110BE then emoji style');
select is(public.name_shape(U&'\+0110be\200d\+01f600', 30), null::text,
          U&'display: U+110BE then joiner and emoji');
select is(public.name_shape(U&'a\+0110ccb', 30), U&'a\+0110ccb',
          U&'display: U+110CC between letters');
select is(public.name_shape(U&'\+0110cc\fe0f', 30), null::text,
          U&'display: U+110CC then emoji style');
select is(public.name_shape(U&'\+0110cc\200d\+01f600', 30), null::text,
          U&'display: U+110CC then joiner and emoji');
select is(public.name_shape(U&'a\+0110cdb', 30), null::text,
          U&'display: U+110CD between letters');
select is(public.name_shape(U&'\+0110cd\fe0f', 30), null::text,
          U&'display: U+110CD then emoji style');
select is(public.name_shape(U&'\+0110cd\200d\+01f600', 30), null::text,
          U&'display: U+110CD then joiner and emoji');
select is(public.name_shape(U&'a\+0110ceb', 30), U&'a\+0110ceb',
          U&'display: U+110CE between letters');
select is(public.name_shape(U&'\+0110ce\fe0f', 30), null::text,
          U&'display: U+110CE then emoji style');
select is(public.name_shape(U&'\+0110ce\200d\+01f600', 30), null::text,
          U&'display: U+110CE then joiner and emoji');
select is(public.name_shape(U&'a\+01342fb', 30), U&'a\+01342fb',
          U&'display: U+1342F between letters');
select is(public.name_shape(U&'\+01342f\fe0f', 30), null::text,
          U&'display: U+1342F then emoji style');
select is(public.name_shape(U&'\+01342f\200d\+01f600', 30), null::text,
          U&'display: U+1342F then joiner and emoji');
select is(public.name_shape(U&'a\+013430b', 30), null::text,
          U&'display: U+13430 between letters');
select is(public.name_shape(U&'\+013430\fe0f', 30), null::text,
          U&'display: U+13430 then emoji style');
select is(public.name_shape(U&'\+013430\200d\+01f600', 30), null::text,
          U&'display: U+13430 then joiner and emoji');
select is(public.name_shape(U&'a\+01343fb', 30), null::text,
          U&'display: U+1343F between letters');
select is(public.name_shape(U&'\+01343f\fe0f', 30), null::text,
          U&'display: U+1343F then emoji style');
select is(public.name_shape(U&'\+01343f\200d\+01f600', 30), null::text,
          U&'display: U+1343F then joiner and emoji');
select is(public.name_shape(U&'a\+013440b', 30), U&'a\+013440b',
          U&'display: U+13440 between letters');
select is(public.name_shape(U&'\+013440\fe0f', 30), null::text,
          U&'display: U+13440 then emoji style');
select is(public.name_shape(U&'\+013440\200d\+01f600', 30), null::text,
          U&'display: U+13440 then joiner and emoji');
select is(public.name_shape(U&'a\+01bc9fb', 30), U&'a\+01bc9fb',
          U&'display: U+1BC9F between letters');
select is(public.name_shape(U&'\+01bc9f\fe0f', 30), null::text,
          U&'display: U+1BC9F then emoji style');
select is(public.name_shape(U&'\+01bc9f\200d\+01f600', 30), null::text,
          U&'display: U+1BC9F then joiner and emoji');
select is(public.name_shape(U&'a\+01bca0b', 30), null::text,
          U&'display: U+1BCA0 between letters');
select is(public.name_shape(U&'\+01bca0\fe0f', 30), null::text,
          U&'display: U+1BCA0 then emoji style');
select is(public.name_shape(U&'\+01bca0\200d\+01f600', 30), null::text,
          U&'display: U+1BCA0 then joiner and emoji');
select is(public.name_shape(U&'a\+01bca3b', 30), null::text,
          U&'display: U+1BCA3 between letters');
select is(public.name_shape(U&'\+01bca3\fe0f', 30), null::text,
          U&'display: U+1BCA3 then emoji style');
select is(public.name_shape(U&'\+01bca3\200d\+01f600', 30), null::text,
          U&'display: U+1BCA3 then joiner and emoji');
select is(public.name_shape(U&'a\+01bca4b', 30), U&'a\+01bca4b',
          U&'display: U+1BCA4 between letters');
select is(public.name_shape(U&'\+01bca4\fe0f', 30), null::text,
          U&'display: U+1BCA4 then emoji style');
select is(public.name_shape(U&'\+01bca4\200d\+01f600', 30), null::text,
          U&'display: U+1BCA4 then joiner and emoji');
select is(public.name_shape(U&'a\+01d172b', 30), U&'a\+01d172b',
          U&'display: U+1D172 between letters');
select is(public.name_shape(U&'\+01d172\fe0f', 30), null::text,
          U&'display: U+1D172 then emoji style');
select is(public.name_shape(U&'\+01d172\200d\+01f600', 30), null::text,
          U&'display: U+1D172 then joiner and emoji');
select is(public.name_shape(U&'a\+01d173b', 30), null::text,
          U&'display: U+1D173 between letters');
select is(public.name_shape(U&'\+01d173\fe0f', 30), null::text,
          U&'display: U+1D173 then emoji style');
select is(public.name_shape(U&'\+01d173\200d\+01f600', 30), null::text,
          U&'display: U+1D173 then joiner and emoji');
select is(public.name_shape(U&'a\+01d17ab', 30), null::text,
          U&'display: U+1D17A between letters');
select is(public.name_shape(U&'\+01d17a\fe0f', 30), null::text,
          U&'display: U+1D17A then emoji style');
select is(public.name_shape(U&'\+01d17a\200d\+01f600', 30), null::text,
          U&'display: U+1D17A then joiner and emoji');
select is(public.name_shape(U&'a\+01d17bb', 30), U&'a\+01d17bb',
          U&'display: U+1D17B between letters');
select is(public.name_shape(U&'\+01d17b\fe0f', 30), null::text,
          U&'display: U+1D17B then emoji style');
select is(public.name_shape(U&'\+01d17b\200d\+01f600', 30), null::text,
          U&'display: U+1D17B then joiner and emoji');
select is(public.name_shape(U&'a\+01efffb', 30), U&'a\+01efffb',
          U&'display: U+1EFFF between letters');
select is(public.name_shape(U&'\+01efff\fe0f', 30), null::text,
          U&'display: U+1EFFF then emoji style');
select is(public.name_shape(U&'\+01efff\200d\+01f600', 30), null::text,
          U&'display: U+1EFFF then joiner and emoji');
select is(public.name_shape(U&'a\+01f000b', 30), U&'a\+01f000b',
          U&'display: U+1F000 between letters');
select is(public.name_shape(U&'\+01f000\fe0f', 30), U&'\+01f000\fe0f',
          U&'display: U+1F000 then emoji style');
select is(public.name_shape(U&'\+01f000\200d\+01f600', 30), U&'\+01f000\200d\+01f600',
          U&'display: U+1F000 then joiner and emoji');
select is(public.name_shape(U&'a\+01f3fab', 30), U&'a\+01f3fab',
          U&'display: U+1F3FA between letters');
select is(public.name_shape(U&'\+01f3fa\fe0f', 30), U&'\+01f3fa\fe0f',
          U&'display: U+1F3FA then emoji style');
select is(public.name_shape(U&'\+01f3fa\200d\+01f600', 30), U&'\+01f3fa\200d\+01f600',
          U&'display: U+1F3FA then joiner and emoji');
select is(public.name_shape(U&'a\+01f3fbb', 30), null::text,
          U&'display: U+1F3FB between letters');
select is(public.name_shape(U&'\+01f3fb\fe0f', 30), null::text,
          U&'display: U+1F3FB then emoji style');
select is(public.name_shape(U&'\+01f3fb\200d\+01f600', 30), null::text,
          U&'display: U+1F3FB then joiner and emoji');
select is(public.name_shape(U&'a\+01f3ffb', 30), null::text,
          U&'display: U+1F3FF between letters');
select is(public.name_shape(U&'\+01f3ff\fe0f', 30), null::text,
          U&'display: U+1F3FF then emoji style');
select is(public.name_shape(U&'\+01f3ff\200d\+01f600', 30), null::text,
          U&'display: U+1F3FF then joiner and emoji');
select is(public.name_shape(U&'a\+01f400b', 30), U&'a\+01f400b',
          U&'display: U+1F400 between letters');
select is(public.name_shape(U&'\+01f400\fe0f', 30), U&'\+01f400\fe0f',
          U&'display: U+1F400 then emoji style');
select is(public.name_shape(U&'\+01f400\200d\+01f600', 30), U&'\+01f400\200d\+01f600',
          U&'display: U+1F400 then joiner and emoji');
select is(public.name_shape(U&'a\+01faffb', 30), U&'a\+01faffb',
          U&'display: U+1FAFF between letters');
select is(public.name_shape(U&'\+01faff\fe0f', 30), U&'\+01faff\fe0f',
          U&'display: U+1FAFF then emoji style');
select is(public.name_shape(U&'\+01faff\200d\+01f600', 30), U&'\+01faff\200d\+01f600',
          U&'display: U+1FAFF then joiner and emoji');
select is(public.name_shape(U&'a\+01fb00b', 30), U&'a\+01fb00b',
          U&'display: U+1FB00 between letters');
select is(public.name_shape(U&'\+01fb00\fe0f', 30), null::text,
          U&'display: U+1FB00 then emoji style');
select is(public.name_shape(U&'\+01fb00\200d\+01f600', 30), null::text,
          U&'display: U+1FB00 then joiner and emoji');
select is(public.name_shape(U&'a\+0e0000b', 30), U&'a\+0e0000b',
          U&'display: U+E0000 between letters');
select is(public.name_shape(U&'\+0e0000\fe0f', 30), null::text,
          U&'display: U+E0000 then emoji style');
select is(public.name_shape(U&'\+0e0000\200d\+01f600', 30), null::text,
          U&'display: U+E0000 then joiner and emoji');
select is(public.name_shape(U&'a\+0e0001b', 30), null::text,
          U&'display: U+E0001 between letters');
select is(public.name_shape(U&'\+0e0001\fe0f', 30), null::text,
          U&'display: U+E0001 then emoji style');
select is(public.name_shape(U&'\+0e0001\200d\+01f600', 30), null::text,
          U&'display: U+E0001 then joiner and emoji');
select is(public.name_shape(U&'a\+0e0002b', 30), U&'a\+0e0002b',
          U&'display: U+E0002 between letters');
select is(public.name_shape(U&'\+0e0002\fe0f', 30), null::text,
          U&'display: U+E0002 then emoji style');
select is(public.name_shape(U&'\+0e0002\200d\+01f600', 30), null::text,
          U&'display: U+E0002 then joiner and emoji');
select is(public.name_shape(U&'a\+0e001fb', 30), U&'a\+0e001fb',
          U&'display: U+E001F between letters');
select is(public.name_shape(U&'\+0e001f\fe0f', 30), null::text,
          U&'display: U+E001F then emoji style');
select is(public.name_shape(U&'\+0e001f\200d\+01f600', 30), null::text,
          U&'display: U+E001F then joiner and emoji');
select is(public.name_shape(U&'a\+0e0020b', 30), null::text,
          U&'display: U+E0020 between letters');
select is(public.name_shape(U&'\+0e0020\fe0f', 30), null::text,
          U&'display: U+E0020 then emoji style');
select is(public.name_shape(U&'\+0e0020\200d\+01f600', 30), null::text,
          U&'display: U+E0020 then joiner and emoji');
select is(public.name_shape(U&'a\+0e007fb', 30), null::text,
          U&'display: U+E007F between letters');
select is(public.name_shape(U&'\+0e007f\fe0f', 30), null::text,
          U&'display: U+E007F then emoji style');
select is(public.name_shape(U&'\+0e007f\200d\+01f600', 30), null::text,
          U&'display: U+E007F then joiner and emoji');
select is(public.name_shape(U&'a\+0e0080b', 30), U&'a\+0e0080b',
          U&'display: U+E0080 between letters');
select is(public.name_shape(U&'\+0e0080\fe0f', 30), null::text,
          U&'display: U+E0080 then emoji style');
select is(public.name_shape(U&'\+0e0080\200d\+01f600', 30), null::text,
          U&'display: U+E0080 then joiner and emoji');
select is(public.name_shape(U&'a\+0e00ffb', 30), U&'a\+0e00ffb',
          U&'display: U+E00FF between letters');
select is(public.name_shape(U&'\+0e00ff\fe0f', 30), null::text,
          U&'display: U+E00FF then emoji style');
select is(public.name_shape(U&'\+0e00ff\200d\+01f600', 30), null::text,
          U&'display: U+E00FF then joiner and emoji');
select is(public.name_shape(U&'a\+0e0100b', 30), null::text,
          U&'display: U+E0100 between letters');
select is(public.name_shape(U&'\+0e0100\fe0f', 30), null::text,
          U&'display: U+E0100 then emoji style');
select is(public.name_shape(U&'\+0e0100\200d\+01f600', 30), null::text,
          U&'display: U+E0100 then joiner and emoji');
select is(public.name_shape(U&'a\+0e01efb', 30), null::text,
          U&'display: U+E01EF between letters');
select is(public.name_shape(U&'\+0e01ef\fe0f', 30), null::text,
          U&'display: U+E01EF then emoji style');
select is(public.name_shape(U&'\+0e01ef\200d\+01f600', 30), null::text,
          U&'display: U+E01EF then joiner and emoji');
select is(public.name_shape(U&'a\+0e01f0b', 30), U&'a\+0e01f0b',
          U&'display: U+E01F0 between letters');
select is(public.name_shape(U&'\+0e01f0\fe0f', 30), null::text,
          U&'display: U+E01F0 then emoji style');
select is(public.name_shape(U&'\+0e01f0\200d\+01f600', 30), null::text,
          U&'display: U+E01F0 then joiner and emoji');

select * from finish();
rollback;
